// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYA9T5F95UVJ4xC2H_QdsbgglwkBmmp0',
    appId: '1:492341470431:web:0b3f8416f0c3474778356a',
    messagingSenderId: '492341470431',
    projectId: 'glucora-90bf4',
    authDomain: 'glucora-90bf4.firebaseapp.com',
    storageBucket: 'glucora-90bf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZBMjP8EQEBUJveR5_5J7VVAnFi4hxhY',
    appId: '1:492341470431:android:5f7fc52e6469ec2b78356a',
    messagingSenderId: '492341470431',
    projectId: 'glucora-90bf4',
    storageBucket: 'glucora-90bf4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuYA9T5F95UVJ4xC2H_QdsbgglwkBmmp0',
    appId: '1:492341470431:web:e3ddb8ad4ff6fc5a78356a',
    messagingSenderId: '492341470431',
    projectId: 'glucora-90bf4',
    authDomain: 'glucora-90bf4.firebaseapp.com',
    storageBucket: 'glucora-90bf4.firebasestorage.app',
  );
}
